# Generated by Django 4.0.3 on 2022-06-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='slug',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
